export const routes = {
  home: '/',
  login: '/login',
  register: '/register',
  dashboard: '/dashboard',
  admin: '/admin',
  adminUsers: '/admin/users',
  adminCriteria: '/admin/criteria',
  adminClassifications: '/admin/classifications',
  adminWorkTables: '/admin/work-tables',
  initiatives: '/initiatives',
  initiativeNew: '/initiatives/new',
  initiative: (id: string) => `/initiatives/${id}`,
  initiativeEdit: (id: string) => `/initiatives/${id}/edit`,
  initiativeEvaluations: (id: string) => `/initiatives/${id}/evaluations`,
  chatNew: '/chat/new',
  chat: (id: string) => `/chat/${id}`,
  evaluations: '/evaluations',
  evaluation: (id: string) => `/evaluations/${id}`,
} as const;
